/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function getWord(word: string): string
export declare function search(queryStr: string, skip: number, limit: number, maxDis: number): string
export declare function editDistance(a: string, b: string): number
