/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function search(queryStr: string, useExactIndex: boolean, useTextIndex: boolean, skip: number, limit: number): void
export declare function editDistance(a: string, b: string): number
